- name: loops demo
  hosts: local
  connection: local
  tasks:
  - name: print names
    anisible.builtin.debug:
     msg: "Hello {{item}}"
    loop:
    - Ramesh
    - Suresh
    - Robert
    - Rahim 