- name: Install packages using loops
  hosts: web
  become: yes
  tasks:
  - name: Installing packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - postfix
    - mysql
    - httpd