- name: demo on filters
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: print the default variables
    ansible.builtin.debug:
     msg: "Hello {{ course| default('Ansible') }}"

  - name: Convert into uppercase
    vars:
     greeting: "Hello Ramesh"
    ansible.builtin.debug:
     msg: "{{ greeting| upper }}"

  - name: convert into lowercase
    vars:
     greeting: "Hello Suresh"
    ansible.builtin.debug:
     msg: "{{ greeting | lower }}"

  - name: Get unique values
    vars:
     numbers: [1,2,3,45,46,3,2,1,6]
    ansible.builtin.debug:
     msg: " {{ numbers | unique }}"

  -  name: print the min and max number
     vars:
      numbers: [1,2,45,34,29,0]
     ansible.builtin.debug:
      msg: " Min: {{ numbers| min }}, Max: {{ numbers| max}}"

  - name: convert map/dictionary to list
    vars:
     course: 
      name: DevOps
      duration: 120HRS
      trainer: SivakumarReddy
    ansible.builtin.debug:
     msg: " {{course | dict2items }} "
      
  - name: covert list to map/dictionary
    vars:
      course:
      - { "key": "name", "value": "DevOps" }
      - { "key": "Time", "value": 120 }
      - { "key": "Trainer", "value": "siva" }   
    ansible.builtin.debug:
      msg: " {{ course| items2dict }}"