- name: command vs shell
  hosts: local
  connection: local
  become: yes
  tasks:
   - name: execute the command
     ansible.builtin.shell: ls -ltr > /tmp/output.txt

- name: command vs shell
  hosts: local
  connection: local
  become: yes
  tasks:
   - name: execute the command
     ansible.builtin.shell: ps -ef|grep ssh
     register: output

   - name: show the output
     ansible.builtin.debug:
        msg: "{{ output.stdout }}"