- name: install nginx server and run
  hosts: web
  tasks: 
  - name: install nginx
    ansible.builtin.package:  #hetrogeneous module that can work for all distributions like ubuntu, linux, redhat
     name: nginx
    state: present