 - name: variables to print
   hosts: web
   vars: #play level, all tasks in this play have access to this
    COURSE: "DevOps with AWS"
    TRAINER: "SivakumarReddy"
    DURATION: "120HRS"
   tasks:
   - name: print the information
     ansible.builtin.debug:
      msg: "Hi, Iam learning {{COURSE}}, duration is: {{DURATION}}, and trainer {{TRAINER}} "
