 - name: variables to print
   hosts: web
   vars_files: #asking ansible to get files from source file 
   - vars.yaml
   tasks:
   - name: print the information
     ansible.builtin.debug:
      msg: "Hi, Iam learning {{COURSE}}, duration is: {{Duration}}, and trainer {{TRAINER}} "
