 - name: variables to print
   hosts: web
   vars_files: #play level, all tasks in this play have access to this
  - vars.yaml
   tasks:
   - name: print the information
     ansible.builtin.debug:
      msg: "Hi, Iam learning {{COURSE}}, duration is: {{Duration}}, and trainer {{TRAINER}} "
